language: python
python:
  - "2.7"
  - "3.4"
# command to install hdf5 library
before_install:
  - sudo apt-get install libhdf5-serial-dev gfortran libopenblas-dev liblapack-dev
# command to install dependencies
install: python setup.py install
# command to run tests
script: nosetests
